roddit/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :users, only: [:new, :create, :index]
  resource :session, only: [:create, :new, :destroy]
  resources :subs, except: [:destroy] do
    resources :posts, except: [:index]
  end
end

roddit/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

roddit/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id        :bigint           not null, primary key
#  title     :string           not null
#  url       :string
#  content   :text
#  sub_id    :integer          not null
#  author_id :integer          not null
#

class Post < ApplicationRecord
    validates :title, :sub_id, :author_id, presence: true
    validates :title, length: {minimum: 1}
    belongs_to :sub,
        primary_key: :id,
        foreign_key: :sub_id,
        class_name: :Sub 
    
    belongs_to :author,
        primary_key: :id,
        foreign_key: :author_id,
        class_name: :User
end

roddit/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint           not null, primary key
#  title        :string           not null
#  description  :string
#  moderator_id :integer          not null
#

class Sub < ApplicationRecord
    validates :moderator_id, null: false
    validates :title, length: {minimum: 1}
    belongs_to :moderator,
        primary_key: :id,
        foreign_key: :moderator_id,
        class_name: :User
    has_many :posts,
        primary_key: :id,
        foreign_key: :sub_id,
        class_name: :Post
end

roddit/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  session_token   :string           not null
#  password_digest :string           not null
#

class User < ApplicationRecord
    validates :username, :session_token, presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :password, length: {minimum: 6, allow_nil: true}

    after_initialize :ensure_session_token
    attr_reader :password

    has_many :subs,
        primary_key: :id,
        foreign_key: :moderator_id,
        class_name: :Sub

    has_many :posts,
        primary_key: :id,
        foreign_key: :author_id,
        class_name: :Post
    
    def password=(password)
        self.password_digest = BCrypt::Password.create(password)
        @password = password
    end

    def is_password?(password)
        pw_digest=BCrypt::Password.new(password_digest)
        pw_digest.is_password?(password)
    end

    def self.find_by_credentials(username,password)
        u = User.find_by(username: username)
        if u && u.is_password?(password)
            u 
        else
            nil
        end
    end

    def self.generate_session_token
        SecureRandom::urlsafe_base64
    end

    def ensure_session_token
        self.session_token ||= self.class.generate_session_token
    end

    def reset_session_token!
        self.session_token = self.class.generate_session_token
        self.save
        self.session_token
    end
end

roddit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def logged_in?
        !!current_user
    end

    def ensure_logged_in
        redirect_to new_session_url unless logged_in?
    end

    def login!(user)
        session[:session_token] = user.reset_session_token!
    end

    def logout!
        current_user.reset_session_token!
        @current_user = nil
        session[:session_token] = nil
    end
end

roddit/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :ensure_logged_in, only: [:new, :create]
    before_action :ensure_author, only: [:edit, :update]
    def ensure_logged_in
        redirect_to new_session_url unless logged_in?
    end

    def ensure_author
        redirect_to new_session_url unless logged_in? && current_user == Post.find_by(id: params[:id]).author
    end
    def new
        render :new
    end

    def create
        @post = current_user.posts.new(title: params[:title], url: params[:url], content: params[:content])
        @post.sub_id = params[:sub_id]
        if @post.save
            redirect_to sub_post_url(@post.sub,@post)
        else
            flash.now[:errors] = @post.errors.full_message
            render :new
        end

    end

    def show
        @post = Post.find_by(id: params[:id])
        render :show
    end
    
    def edit
        @post = Post.find_by(id: params[:id])
        render :edit
    end

    def update
        @post = Post.find_by(id: params[:id])
        @post.title = params[:title]
        @post.url = params[:url]
        @post.content = params[:content]
        if @post.save
            redirect_to sub_post_url(@post.sub,@post)
        else
            flash.now[:errors] = @post.errors.full_message
            render :edit
        end
    end
end
# == Schema Information
#
# Table name: posts
#
#  id        :bigint           not null, primary key
#  title     :string           not null
#  url       :string
#  content   :text
#  sub_id    :integer          not null
#  author_id :integer          not null

roddit/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        render :new
    end

    def create
        u = User.find_by_credentials(user_params[:username],
                                    user_params[:password])
        if u
            login!(u)
            redirect_to users_url
        else
            flash.now[:errors] = ["Invalid username or password"]
            render :new
        end
    end

    def destroy
        logout!
        redirect_to new_session_url
    end

    def user_params
        params.require(:user).permit(:username,:password )
    end
end

roddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController
    before_action :ensure_logged_in, only: [:new,:create,]
    before_action :ensure_moderator, only: [:edit, :update]
    def ensure_moderator
        redirect_to new_session_url unless logged_in? && (current_user == Sub.find_by(id: params[:id]).moderator)
    end

    def ensure_logged_in
        redirect_to new_session_url unless logged_in?
    end
    def edit
        @sub = Sub.find_by(id: params[:id])
        render :edit
    end
    def new
        render :new
    end
    def create
        @sub = current_user.subs.new(title: params[:title],description: params[:description])
        if @sub.save
            redirect_to sub_url(@sub)
        else
            render :new
        end
    end
    def show
        if @sub = Sub.find_by(id: params[:id])
            render :show
        # else
        #     redirect_to subs_url
        end
    end
    def update
        @sub = Sub.find_by(id: params[:id])
        @sub.title = params[:title]
        @sub.description = params[:description]
        if @sub.save
            redirect_to sub_url(@sub)
        else
            flash.now[:errors] = @sub.errors.full_messages
            render :edit
        end
    end
    def index
        render :index
    end
end

roddit/app/controllers/users_controller.rb
class UsersController < ApplicationController 
    def new
        render :new
    end

    def create
        u = User.new(:username => user_params[:username], password: user_params[:password])
        if u.save
            login!(u)
            redirect_to users_url
        else
            flash.now[:errors] = u.errors.full_messages
            render :new
        end
    end

    private
    def user_params
        params.require(:user).permit(:username,:password )
    end
end

roddit/app/helpers/application_helper.rb
module ApplicationHelper
    def auth_token
        "<input type=\"hidden\" name=\"authenticity_token\" 
        value=\"#{form_authenticity_token}\">".html_safe
    end

    def change_method(method)
        "<input type=\"hidden\" name=\"_method\" 
        value=\"#{method}\">".html_safe
    end
end

roddit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roddit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

roddit/app/views/posts/edit.html.erb
<%= flash.now[:errors] %>
<form action="<%= sub_post_url(@post.sub,@post) %>" method="POST">
    <%= auth_token %>
    <%= change_method("PATCH")%>
    <label>Title
        <input type="text" name="title" value="<%= @post.title %>">
    </label>
    <label>Url
        <input type="text" name="url" value=<%= @post.url %>>
    </label>
    <label>content
        <input type="text" name="content" value=<%= @post.content %>>
    </label>
    <input type="submit" name="Create Sub">
</form>

roddit/app/views/posts/new.html.erb
<%= flash.now[:errors] %>
<form action="<%= sub_posts_url %>" method="POST">
    <%= auth_token %>
    <label>Title
        <input type="text" name="title">
    </label>
    <label>Url
        <input type="text" name="url">
    </label>
    <label>content
        <input type="text" name="content">
    </label>
    <input type="submit" name="Create Sub">
</form>

roddit/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h3><%= @post.url %></h3>
<span><%= @post.content%></span>
<a href="<%= edit_sub_post_url(@post.sub,@post) %>">Edit</a>

roddit/app/views/subs/edit.html.erb
<%= flash.now[:errors] %>
<form action="<%= sub_url(@sub) %>" method="POST">
    <%= auth_token %>
    <%= change_method("PATCH") %>
    <label>Title
        <input type="text" name="title" value="<%= @sub.title %>">
    </label>
    <label>description
        <input type="text" name="description" value="<%= @sub.description %>">
    </label>
    <input type="submit" name="Create Sub">

roddit/app/views/subs/index.html.erb
<ul><%Sub.all.each do |sub|%>
    <li><a href="<%= sub_url(sub) %>"><%= sub.title %></li>
<%end%></ul>

roddit/app/views/subs/new.html.erb
<form action="<%= subs_url %>" method="POST">
    <%= auth_token %>
    <label>Title
        <input type="text" name="title">
    </label>
    <label>description
        <input type="text" name="description">
    </label>
    <input type="submit" name="Create Sub">
</form>

roddit/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<p><%= @sub.description%></p>
<a href="<%= new_sub_post_url(@sub) %>">New Post</a>
<ul>
<%@sub.posts.each do |post| %>
    <li><a href="<%= sub_post_url(@sub,post) %>">
    <%=  post.title%></a></li>
<% end%>
</ul>

roddit/app/views/users/index.html.erb
Hello <%= current_user.username %>
<form method="POST" action="<%= session_url %>">
<%= auth_token %>
<%= change_method("DELETE") %>
<input type="submit" value="logout">
</form>